name: awesome_music_rebased
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  audio_service: ^0.18.0
  audio_session: ^0.1.6+1
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.3
  convert: ^3.0.1
  cupertino_icons: ^1.0.2
  dart_des: ^1.0.0
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flip_card: ^0.5.0
  flutter:
    sdk: flutter
  flutter_cache: ^0.1.0
  flutter_downloader: 
    git:
      url: https://github.com/fluttercommunity/flutter_downloader.git
      ref: 2b7b528585af4c5c0b61e818e425735182e50e1d
  get: ^4.3.8
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  jiosaavn_wrapper:
    # git: https://github.com/teamDrt280320/jiosaavn_wrapper
    path: ../jiosaavn_wrapper
  just_audio: ^0.9.11
  just_audio_background: ^0.0.1-beta.1
  lint: ^1.7.2
  lottie: ^1.2.1
  marquee: ^2.2.0
  marquee_text: ^2.0.0
  palette_generator: ^0.3.1
  path_provider: ^2.0.5
  permission_handler: ^8.1.6
  show_up_animation: ^2.0.0

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - 'assets/lottie/'
